title: "nbaertsch"
owner: "nixknack"
url: "https://nbaertsch.github.io"
baseurl: "/"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "noah.baertsch@gmail.com"
github: "nbaertsch"
linkedin: "noah-baertsch-9a23b9119"
twitter: "nix_knack"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "Whats Enumeration?"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
# plugins
plugins:
  - jemoji
